version: '3.8'

services:
  mysql:
    restart: always
    image: mariadb:10.11
    command: ['mysqld','--character-set-server=utf8mb4']
    volumes:
      - databasevolume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: openemr
      MYSQL_USER: openemr
      MYSQL_PASSWORD: openemr
    ports:
      - "3306:3306"
    networks:
      - aci-network

  iris-emr:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${HOST_HTTP_PORT:-8080}:80"
      - "${HOST_HTTPS_PORT:-8443}:443"
    volumes:
      - logvolume:/var/log
      - sitevolume:/var/www/localhost/htdocs/openemr/sites
      - uploadvolume:/var/www/localhost/htdocs/uploads
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: openemr
      MYSQL_PASSWORD: openemr
      MYSQL_DATABASE: openemr
      OE_USER: admin
      OE_PASS: pass
      SITE: americancaregivers
      # Application environment
      DB_HOST: mysql
      DB_NAME: openemr
      DB_USER: openemr
      DB_PASS: openemr
      APP_ENV: development
    depends_on:
      - mysql
    networks:
      - aci-network

volumes:
  logvolume: {}
  sitevolume: {}
  databasevolume: {}
  uploadvolume: {}

networks:
  aci-network:
    driver: bridge

